"""Added category column to Product

Revision ID: 662d071abd6b
Revises: 
Create Date: 2025-04-07 00:55:26.628003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662d071abd6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
